name: 'Call Shared Workflow to Validate PR Title'

on:
  workflow_dispatch:

jobs:
  validate-title:
    uses: clouddrove-sandbox/terraform-shared-workflows/.github/workflows/validate-pr-title.yml@master
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      
