name: 'Call Shared Workflow to Validate PR Title'

on:
  pull_request_target:
    types:
      - fix
      - feat
     

jobs:
  validate-title:
    uses: clouddrove-sandbox/terraform-shared-workflows/.github/workflows/validate-pr-title.yml@master
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      
